
from typing import Any, Dict, List, Optional, Protocol, runtime_checkable

from datasets import ActiveDataset
from entry.demo.web.models.requests import ActiveLearningConfigRequest
from entry.demo.web.models.responses import (ActiveLearningConfigResponse,
                                             ActiveLearningStateResponse)


@runtime_checkable
class ActiveLearningProtocol(Protocol):
    def update_feature_dict_keys(self, workspace_id: str, old_base_path, new_base_path): ...

    async def get_feature_dict(self, workspace_id: str, batch_size, device, active_dataset: ActiveDataset): ...

    def get_state(self, workspace_id: str) -> ActiveLearningStateResponse: ...

    def get_annotated_set(self, workspace_id: str) -> List[str]: ...

    def get_train_set(self, workspace_id: str) -> List[str]: ...

    def get_pool_set(self, workspace_id: str) -> List[str]: ...

    def get_selected_set(self, workspace_id: str) -> List[Any]: ...

    def get_selected_image(self, workspace_id: str) -> dict: ...

    async def update_config(self, workspace_id: str,
                            config_request: ActiveLearningConfigRequest) -> ActiveLearningConfigResponse: ...

    def get_config(self, workspace_id: str) -> dict[str, str | Any]: ...

    def get_param_config(self, workspace_id: str) -> dict[str, str | Any]: ...

    async def active_select(self, workspace_id: str, train_set, pool_set, budget, model_ckpt, batch_size, device,
                            loaded_feature_weight, sharp_factor, loaded_feature_only): ...

    def predict_pseudo_label(self, workspace_id: str, image_pil): ...

    def clear(self, workspace_id: str): ...

    def delete_workspace(self, workspace_id: str): ...

    def get_workspace_stats(self) -> Dict[str, Any]: ...
